### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by oliviercherrier** [ksahnine/jwt-secured-api-node#1]
Bonjour,

lorsque je tente de lancer le serveur via `npm start`, j'ai le message d'erreur suivant:

```
npm ERR! jwt-secured-api-node@0.0.1 start: `export DEBUG=app && node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jwt-secured-api-node@0.0.1 start script 'export DEBUG=app
 && node ./bin/www'.
```

Merci de ton aide,

Olivier.

**Comment by ksahnine** [comment]
Bonjour,

Quelle est la version de _node_/_npm_ utilisée (via la commande `npm --verbose start`) ?
Par ailleurs, quel OS utilises-tu (perso, suis sous Mac OS) ?

Si tu travailles sous Windows via un shell DOS, tu dois adapter la rubrique `scripts` dans le descripteur `packages.json`. 
Sous DOS, j'imagine que la commande devrait plutôt être du genre : 

```
  "scripts": {
    "start": "set DEBUG=app & node ./bin/www"
  },
```

**Comment by oliviercherrier** [comment]
Bonjour,

merci de ta réponse rapide.

En effet, je suis sous Windows... ton fix fonctionne parfaitement.

Olivier.
